-- Assign every existing order a request from the imported request list.
-- New payment functions use the same list at order completion.
with request_templates(request) as (
values
  ('Something beautiful for me and my soulmate.'),
  ('A love quote for me and the person I’m meant to be with.'),
  ('Write something about two souls finding each other.'),
  ('Something romantic about a love that feels God-sent.'),
  ('A quote about me and my future husband.'),
  ('Something for me and my future wife about growing together.'),
  ('Write something about finding your soulmate at the right time.'),
  ('A deep quote about two hearts becoming one.'),
  ('Something inspirational about building a forever relationship.'),
  ('A message about loving someone through every season of life.'),
  ('Something about God bringing two people together.'),
  ('A quote about trusting God with your future love.'),
  ('Write something about a soulmate who is also your prayer partner.'),
  ('Something about waiting for the person God has prepared for me.'),
  ('A faith-based love quote for me and my future partner.'),
  ('Something about God writing our love story.'),
  ('A message about trusting God''s timing when it comes to love.'),
  ('Write something about praying for your future spouse.'),
  ('Something romantic about two people growing closer to God together.'),
  ('A quote about a relationship built on faith, not just feelings.'),
  ('Something about building an unbreakable bond with your soulmate.'),
  ('A quote about staying together through hard times.'),
  ('Write something about a love that becomes stronger with every challenge.'),
  ('Something about choosing each other every day.'),
  ('A message about never giving up on the person you love.'),
  ('Something about emotional and spiritual connection between soulmates.'),
  ('A quote about two people growing stronger together.'),
  ('Write something about protecting the bond between two hearts.'),
  ('Something about love that survives distance and difficult seasons.'),
  ('A message about creating a relationship that lasts forever.'),
  ('Something for my future relationship and the love we will build.'),
  ('Write something about my future soulmate and our beautiful life together.'),
  ('A quote about the future I hope to have with my partner.'),
  ('Something about building a peaceful future with the person I love.'),
  ('Write something about growing old together.'),
  ('Something about the home and life my soulmate and I will build.'),
  ('A romantic message about our future marriage.'),
  ('Something about creating memories with your soulmate for a lifetime.'),
  ('A quote about loving someone through every chapter of life.'),
  ('Write something about the future God has planned for two people in love.'),
  ('Something deep about loving someone beyond words.'),
  ('A quote about finding someone who understands your soul.'),
  ('Write something about feeling safe with your soulmate.'),
  ('Something about a love that feels like home.'),
  ('A deep message about being completely understood by the person you love.'),
  ('Something about two wounded hearts healing together.'),
  ('A quote about finding peace in someone''s presence.'),
  ('Write something about a love that brings out the best in both people.'),
  ('Something about being loved during your weakest moments.'),
  ('A message about having someone who stays when life gets difficult.'),
  ('Write a prayer for me and my future soulmate.'),
  ('A prayer for a strong and healthy relationship.'),
  ('Something I can pray over my future marriage.'),
  ('Write a prayer asking God to protect our love.'),
  ('A prayer for two people who want to grow together spiritually.'),
  ('Something about praying for my future spouse every night.'),
  ('Write a prayer for patience while waiting for true love.'),
  ('A prayer for a relationship that honors God.'),
  ('Something about asking God to strengthen our bond.'),
  ('Write a beautiful prayer for me and my soulmate to stay together through every storm.'),
  ('Something romantic but also inspirational for my soulmate.'),
  ('A love quote that feels deep and meaningful.'),
  ('Write something that makes my soulmate feel truly loved.'),
  ('Something sweet about being grateful for the person God gave you.'),
  ('A message about appreciating your partner before it''s too late.'),
  ('Something romantic about choosing love over pride.'),
  ('Write something about never taking your soulmate for granted.'),
  ('A quote about making your partner feel valued every day.'),
  ('Something about loving intentionally, not casually.'),
  ('A message about making your relationship your safe place.'),
  ('Something for couples going through a difficult season.'),
  ('Write something encouraging for me and my partner during hard times.'),
  ('A faith-based message about not giving up on love.'),
  ('Something about trusting God when your relationship is struggling.'),
  ('A quote about healing after misunderstandings between two people.'),
  ('Write something about choosing forgiveness in a relationship.'),
  ('Something about staying connected when life becomes overwhelming.'),
  ('A message for couples who are currently separated by distance.'),
  ('Something about believing that difficult seasons can strengthen love.'),
  ('Write an inspirational message for someone afraid of losing their soulmate.'),
  ('Give me an affirmation for me and my soulmate.'),
  ('Write something I can say every morning about my future love.'),
  ('A powerful affirmation about attracting a healthy, God-centered relationship.'),
  ('Something positive about becoming ready for my future spouse.'),
  ('Write an affirmation about trusting God''s plan for my love life.'),
  ('Something about believing I deserve a faithful and genuine love.'),
  ('Give me a soulmate affirmation about loyalty and commitment.'),
  ('Write something about becoming the kind of partner I want to attract.'),
  ('An affirmation for building a relationship based on faith and trust.'),
  ('Something I can read when I feel like I''ll never find my person.'),
  ('Can you write something for me and my soulmate that feels like our love was written by God?'),
  ('I want something that describes two people who have been through everything and still choose each other.'),
  ('Can you make me a romantic quote about my future husband and the family we will build?'),
  ('I want a beautiful message about finding my person after years of waiting.'),
  ('Write something about two people whose love brings them closer to God.'),
  ('Can you create something about a soulmate who feels like an answered prayer?'),
  ('I want a deep message about loving my partner through every season, good or bad.'),
  ('Write something emotional about two people promising to grow old together.'),
  ('Can you create a faith-based love message about God protecting our relationship from anything that tries to break us?'),
  ('I want something powerful about two soulmates choosing each other, trusting God, growing together, and building a love that lasts a lifetime.'),
  ('Can you write a sweet message for me and my soulmate about how our connection feels different from anything I''ve known before?'),
  ('I need a short love quote about meeting the right person after going through so much.'),
  ('Something for my future husband about how I’m praying for the man God wants for me.'),
  ('Can you write a heartfelt message about two people who found each other when neither was looking?'),
  ('I want something about loving someone who makes you feel closer to God.'),
  ('Write a romantic caption about a soulmate who feels like home after a long journey.'),
  ('Can you make a faith-based quote about God preparing two hearts for each other?'),
  ('Something emotional for couples who have been together for years and still choose each other.'),
  ('I need a message about trusting that the right love will come at the right time.'),
  ('Write something about a relationship where both people pray for each other and grow together.'),
  ('Can you create a short soulmate quote about divine timing and genuine love?'),
  ('Something for my partner about how grateful I am that God allowed our paths to cross.'),
  ('I want a deep message about finding someone who stays even when life isn''t easy.'),
  ('Write something about a love that is peaceful instead of confusing.'),
  ('Can you create an inspirational message about waiting without losing hope in love?'),
  ('Something romantic about two people building a future with God at the center.'),
  ('I need a quote about being patient while God prepares the person meant for me.'),
  ('Write a message about loving my soulmate with patience, grace, and understanding.'),
  ('Can you make something about how real love grows stronger when both people keep God first?'),
  ('Something for my future wife about the life, home, and faith we will share together.'),
  ('I want a heartfelt quote about being loved for who you truly are.'),
  ('Write something about a soulmate who sees your flaws but chooses to love you anyway.'),
  ('Can you make a message about protecting a relationship through prayer and communication?'),
  ('Something inspirational for a couple who is trying to rebuild their trust.'),
  ('I need a romantic message about choosing your partner even on ordinary days.'),
  ('Write something about a love that doesn''t need to be perfect to be meaningful.'),
  ('Can you create a faith-filled message for someone praying for their future spouse?'),
  ('Something about God removing the wrong people so the right person can find you.'),
  ('I want a quote about a relationship that feels peaceful, loyal, and genuine.'),
  ('Write something about two people becoming better versions of themselves because of their love.'),
  ('Can you make a beautiful message about my soulmate being one of God''s greatest blessings?'),
  ('Something short for a couple celebrating another year together.'),
  ('I need a message about staying faithful to each other when life gets busy.'),
  ('Write a romantic quote about holding onto each other through every storm.'),
  ('Can you create something about a love that was worth waiting for?'),
  ('Something for someone who is tired of temporary relationships and wants something lasting.'),
  ('I want a message about trusting God after experiencing heartbreak.'),
  ('Write something about how the right person will bring peace, not constant uncertainty.'),
  ('Can you make a soulmate quote about two hearts meeting at exactly the right moment?'),
  ('Something about loving your partner through growth, change, and different seasons.'),
  ('I need a faith-based caption for a couple who believes God brought them together.'),
  ('Write something about being thankful for a partner who supports your dreams and faith.'),
  ('Can you create a message about praying together before making important decisions as a couple?'),
  ('Something romantic about growing old with the person who knows your whole story.'),
  ('I want a quote about being someone''s safe place and finding a safe place in them.'),
  ('Write something about a relationship where forgiveness is stronger than pride.'),
  ('Can you make an inspirational message about not comparing your relationship to anyone else''s?'),
  ('Something about letting God guide your relationship instead of rushing the future.'),
  ('I need a romantic message for someone who believes their soulmate is worth waiting for.'),
  ('Write something about two people whose love becomes stronger because they keep choosing grace.'),
  ('Can you create a short prayer for my future husband and the family we may build?'),
  ('Something about asking God to give me wisdom when choosing a life partner.'),
  ('I want a prayer for a couple who wants their relationship to remain strong through every season.'),
  ('Write a prayer for protection over my relationship and the bond we share.'),
  ('Can you create a prayer for healing after a difficult season in a relationship?'),
  ('Something about asking God to help two people understand each other better.'),
  ('I need a prayer for my future wife and the love we haven''t found yet.'),
  ('Write a prayer asking God to help us love each other with patience and kindness.'),
  ('Can you create a faith-based prayer for couples dealing with distance?'),
  ('Something about praying for a relationship that leads both people toward their purpose.'),
  ('I want a prayer for a soulmate relationship built on honesty, loyalty, and faith.'),
  ('Write something for someone who wonders if God still has a love story for them.'),
  ('Can you make a message for someone who has been single for a long time and is losing hope?'),
  ('Something about believing that being alone right now doesn''t mean you''ll always be alone.'),
  ('I need an inspirational quote for someone healing before entering a new relationship.'),
  ('Write something about becoming emotionally and spiritually ready for the right person.'),
  ('Can you create a message about not settling for a relationship that takes away your peace?'),
  ('Something about learning to love yourself while waiting for your soulmate.'),
  ('I want a faith-based reminder that God''s timing in love doesn''t need to match mine.'),
  ('Write something about letting go of an old relationship so you can make room for something healthier.'),
  ('Can you create an inspirational message about heartbreak not being the end of your love story?'),
  ('Something for someone who keeps asking God when their person will arrive.'),
  ('I need a quote about trusting the journey even when everyone around you seems to be finding love.'),
  ('Write something about God knowing the person your heart needs before you even meet them.'),
  ('Can you make a message about not forcing a connection that God isn''t asking you to hold onto?'),
  ('Something about recognizing a healthy love through peace, respect, consistency, and faith.'),
  ('I want a romantic quote about a partner who feels like both best friend and soulmate.'),
  ('Write something about laughing together, praying together, and growing together.'),
  ('Can you create a message about the little things that make a long-term relationship beautiful?'),
  ('Something about waking up beside the same person and still being grateful for them.'),
  ('I need a love quote about choosing kindness during disagreements.'),
  ('Write something about keeping romance alive while building a real life together.'),
  ('Can you make an inspirational message about friendship being the foundation of lasting love?'),
  ('Something about two people supporting each other''s spiritual growth.'),
  ('I want a message about being proud of the person your partner is becoming.'),
  ('Write something about celebrating your soulmate''s small victories as if they were your own.'),
  ('Can you create a quote about loyalty when nobody else is watching?'),
  ('Something about loving someone enough to communicate instead of walking away.'),
  ('I need a message about building trust slowly and protecting it carefully.'),
  ('Write something about a love that becomes deeper with every year.'),
  ('Can you make a romantic caption about still getting butterflies after years together?'),
  ('Something about being grateful for a partner who makes ordinary moments feel special.'),
  ('I want a message about creating a marriage where both people feel heard and valued.'),
  ('Write something about keeping God at the center while still enjoying the romance of love.'),
  ('Can you create a beautiful quote about two people praying for the same future?'),
  ('Something about a soulmate who encourages you to become who God created you to be.'),
  ('I need a message about loving someone without trying to change who they are.'),
  ('Write something about a relationship built on commitment rather than temporary feelings.'),
  ('Can you make a powerful message about two people deciding that their love is worth fighting for in healthy ways?'),
  ('Something about finding the courage to believe in love again after being hurt.'),
  ('I want a quote about a future relationship filled with peace, laughter, prayer, and loyalty.'),
  ('Write something about God''s blessing over a love that is built with patience and intention.'),
  ('Can you create a final message about two soulmates growing old together while keeping God at the center of their home?')
), selected_requests as (
  select
    orders.id,
    picked.request
  from public.digital_orders as orders
  cross join lateral (
    select request
    from request_templates
    order by random()
    limit 1
  ) as picked
)
update public.digital_orders as orders
set
  personalized_request = selected_requests.request,
  updated_at = now()
from selected_requests
where orders.id = selected_requests.id;

update public.donations as donations
set supporter_message = orders.personalized_request
from public.digital_orders as orders
where orders.donation_id = donations.id
  and orders.personalized_request is not null;
